/*
 * This source file was generated by the Gradle 'init' task
 */
package org.gal.cmscli

import org.gal.cmscli.dsl.ItemType
import org.gal.cmscli.finder.findSmartEditBeansFile
import org.gal.cmscli.finder.findSmartEditComponentsFile

private const val ITEM_TYPES_CLOSING_TAG = "</itemtypes>"

fun main() {
    val itemTypes = generateComponents()
    val componentFile = findSmartEditComponentsFile()
    val beanFile = findSmartEditBeansFile()
    componentFile?.let {
        // TODO: enhance performances using RandomAccessFile to avoid rewriting all file
        val oldContent = it.readText()
        val xmlToAppend = itemTypes.map(ItemType::toXml)
            .joinToString(System.lineSeparator())
        val newContent = oldContent.replace(
            ITEM_TYPES_CLOSING_TAG,
            "$xmlToAppend${System.lineSeparator()}$ITEM_TYPES_CLOSING_TAG"
        )
        componentFile.writeText(newContent)
    }
    componentFile?.also { println("New components are generated in ${it.absolutePath}") }
}

